ecmwf/anemoi-utils

src/anemoi/utils/sanitise.py

This is to because on mac-os, `sanitise("2021-01-03T12:00:00")` was treating the string as a url and returning "2021-01-03t12:00:00"  (with lowercase 't')

make-sanitise-string-less-global

---

CHANGELOG.md
src/anemoi/utils/cli.py

This PR allows subcommands to have a different name than their file name via an optional attribute `command`
Usage:
```python
class MyCommand(Command):
command = "fancy-command"
```
Will then become `anemoi-package fancy-command` instead of `anemoi-package mycommand`
If the `command` attribute is not present in the class, the filename is used. I suggest we use that as the default, and only add a `command` if an explicit rename is required.

Optional naming of subcommands

---

.github/ci-hpc-config.yml
CHANGELOG.md
pyproject.toml
pytest.ini

Adds the `skip_on_hpc` pytest marker, and deselects it in the pytest command that is run on the HPC.
Tests can then be skipped by doing:
```python
@pytest.mark.skip_on_hpc
def test_something():
pass
````

Add a skip_on_hpc pytest marker

---

.github/workflows/changelog-pr-update.yml
.github/workflows/changelog-release-update.yml

`utils` will no longer require every PR to add to the changelog, in fact they should not. 
Instead the PR title will be used in the release log and edited by the release manager. 
These notes will then be included in the changelog in a PR to develop.
- No longer require changelog updates
- Autoupdate Changelog on release
If this PR is to be reverted in the future, the changelog can be easily reconstructed.

chore: Update CHANGELOG Requirements

---

CHANGELOG.md
src/anemoi/utils/compatibility.py
tests/test_compatibility.py

Provide a way to alias kwargs in functions.
```python
@aliases(a="b", c=["d", "e"])
def func(a, c):
return a, c
func(a=1, c=2)  # (1, 2)
func(b=1, d=2)  # (1, 2)
```

feat: Add aliases decorator

---

src/anemoi/utils/commands/requests.py
src/anemoi/utils/mars/requests.py

As the title says. Takes an input requests file in json format and outputs a mars request.
Example:
```
anemoi-utils requests input.json output.req --verb archive
```

Add requests command for json to mars format

---

src/anemoi/utils/config.py

This PR adds support to cast `omegaconf.DictConfig` and `omegaconf.ListConfig` to `DotDict`

feat: add omegaconf dict and list as input to DotDict

---

src/anemoi/utils/commands/requests.py

So that `anemoi-utils requests` can accept input from stdin. Then input can be piped like:
`tool-that-generates-requests | anemoi-utils requests - myrequest.req`

feat(requests): read input from stdin

---

pyproject.toml

Set boto3 version to avoid https://stackoverflow.com/questions/79375793/s3uploadfailederror-due-to-missingcontentlength-when-calling-putobject-in-mlflow
Then the dependecy to boto3 in anemoi-registry should be removed and replaced by a dependency to anemoi-utils[s3].

fix: add optional dependency. boto3 <= 1.36

---

src/anemoi/utils/provenance.py

Iterate over copy of sys.modules instead of directly. See https://github.com/ecmwf/anemoi-utils/issues/126
-   [x] Bug fix (non-breaking change which fixes an issue)
Closes #126
-   [x] I have performed a self-review of my code
-   [] I ran the [complete Pytest test](https://anemoi.readthedocs.io/projects/training/en/latest/dev/testing.html) suite locally, and they pass
I got lots of errors, but they seem to be related to credentials for an s3 storage.
========================================== 8 failed, 151 …

fix: Iterate over copy of sys.modules.

---

src/anemoi/utils/testing.py

In get_test_archive from the testing utilities, remove the archive file after unpacking it. This fixes a problem in integration tests where the collection of temporary files exceeded disk quota after several tests. Compare https://github.com/ecmwf/anemoi-core/pull/217
Issue: In the integration tests, we remove the directory containing the unpacked archive after each test but don't have the dir name for the folder containing the archive file itself (to clean this up as well). After a few integration tests, the collection of temporary archive files exceeds the disk quota.
Solution: This PR removes the archive file after unpacking it. I.e. we clean up in between tests and not just at the end of pytest.
Alternative: return both paths (to archive and unpacked archive) such that they can be …

fix: remove archive file after unpacking

---

src/anemoi/utils/testing.py

Problem: If an archive is downloaded twice in the same pytest run, we unpack the archive and write it to the existing temp directory containing the unpacked archive
Solution: If the dir with the unpacked archive already exists, return the path to the directory directly
-   [x] Bug fix (non-breaking change which fixes an issue)

fix: do not write to existing dir

---

src/anemoi/utils/mlflow/auth.py

We did not properly protect the mlflow file. 
This puts a check and chmod in the load function so people's existing token file will be protected next time it's loaded. 

feat: Protect mlflow token file

---

pyproject.toml

Regular mlflow pulls in things like scikit-learn, which are not needed here. We only use the MlflowClient, so mlflow-skinny is enough.

feat(deps): Use mlflow-skinny instead of mlflow

---

src/anemoi/utils/config.py

Issue only one warning when updating DotDict

fix: remove too many warnings

---

src/anemoi/utils/testing.py

Remove the skip_slow_tests decorator as we use pytest markers to mark slow tests in the downstream repos. Requires https://github.com/ecmwf/anemoi-datasets/pull/399 to be merged first
Make markers and cli for slow tests consistent across the anemoi packages.
https://github.com/ecmwf/anemoi-core/issues/257
By opening this pull request, I affirm that all …

refactor: remove skip_slow_tests decorator from utils

---

src/anemoi/utils/mlflow/auth.py
tests/test_mlflow_auth.py

This is a support PR for ecmwf/anemoi-core#469. My basic understanding is that the authentication processes are applicable to AML mlflow logging, since lots of credentials are required to setup the workspace in the first place. So, this creates a PassiveAuth authenticator to allow the AnemoiAzureMlflowLogger to be a child class of the AnemoiMlflowLogger parent class, just silently ignoring all the TokenAuth steps.
New feature: supports AML mlflow logging.
None open but happy to open one if necessary.
See ecmwf/anemoi-core#469 discussion
---
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also …

feat: NoAuth for AML mlflow Logging

---

src/anemoi/utils/checkpoints.py
tests/test_checkpoints.py

Checkpoint rebuilding can be quite slow for large models, as `ZIP_DEFLATED` was being used
Switching to `ZIP_STORED` for no compression results in a large speed up, and since torch checkpoints contain already-compressed tensor data, `ZIP_STORED` gives speed gains with minimal size penalty.
```
=== BENCHMARK RESULTS ===
Edit time: 3.52 seconds
Original size: 1262.4 MB
Output file size: 1262.4 MB
Throughput: 358.9 MB/s
```
Used to take 117 secs, now 3.52, so 33x
- Also adds tests for the checkpoint code to ensure compatability
- Reworked the code for clarity
> [!NOTE]
> New checkpoints have been run with inference and appear fine
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have …

feat: Speedup checkpoint editing - remove compression

---

pyproject.toml
src/anemoi/utils/registry.py
tests/test_registry.py

Add aliases to the registry. The same filter, input, etc can be registered with a canonical name and some aliases.
This will allow migration of filter names to something more consistent while keeping backwards compatibility.
By opening this pull request, I affirm that all authors agree to the [Contributor License …

feat: add aliases to registry

---

src/anemoi/utils/remote/s3.py

Increases the s3 chunk size from 1 MB to 10 MB.
Issues when writing objects to store.

fix: Update s3 chunk size to 10 MB

---

src/anemoi/utils/commands/metadata.py

Respect the yaml or json flags in the metadata get

fix: Use `yaml` and `json` flag in metadata get command
