- CHANGELOG.md
- pyproject.toml
create dependency on wcwidth. MIT licence.
> Update pyproject.toml with wcwidth used for anemoi.utils.text.

- CHANGELOG.md
- src/anemoi/utils/provenance.py
- Get translation dictionary between import name to distribution name
Closes #10
> Feature: Add distribution name method

- .pre-commit-config.yaml
- CHANGELOG.md
- docs/conf.py
- docs/index.rst
----
📚 Documentation preview 📚: https://anemoi-utils--20.org.readthedocs.build/en/20/
> add link to transform

- CHANGELOG.md
- src/anemoi/utils/provenance.py
> [draft] bugfix: fully resolve mount points

- src/anemoi/utils/remote/__init__.py
> feat: bugfix

- src/anemoi/utils/remote/__init__.py
> feat: re-add default values in transfer function

- src/anemoi/utils/caching.py
> chore: fix misleading comment

- pyproject.toml
- src/anemoi/utils/remote/__init__.py
> feat: add robust requests

- src/anemoi/utils/registry.py
- tests/test_remote.py
-   [x] New feature (non-breaking change which adds functionality)
-   [x] I have performed a self-review of my code …
> feat: accept hyphens in factory names

- src/anemoi/utils/registry.py
-   [x] Bug fix (non-breaking change which fixes an issue) …
> fix: support plugin errors

- src/anemoi/utils/registry.py
> fix: plugin name on error

- docs/conf.py
> docs: add links to GitHub 

- src/anemoi/utils/remote/__init__.py
> docs: fix comment

- src/anemoi/utils/config.py
> feat: add generic env variables to override anemoi user config

- src/anemoi/utils/testing.py
-   [x] New feature (non-breaking change which adds functionality) …
> feat: more testing support functions

- .readthedocs.yaml
- docs/Makefile
- docs/_templates/apidoc/package.rst.jinja
- docs/index.rst
- docs/scripts/api_build.sh
- pyproject.toml
> docs: add api

- src/anemoi/utils/registry.py
Adds generic typing for the registry class. With this, it is then possible to do as follows:
```python
foo_registry = Registry[FooBase](__name__)
foo = foo_registry.from_config(some_config)
```
which will allow static type checkers and language servers in IDEs (such as pylance in VSCode) to infer that `foo` is of type (or a subclass of) `FooBase`. After this PR is merged, we can modify all instantiations of registries to have additional type annotations.
P.S.: I would suggest gradually introducing generic typing in the rest of anemoi where possible. 
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] …
> feat: add generic types for registry

- src/anemoi/utils/grids.py
> feat: grid-support

- src/anemoi/utils/remote/s3.py
> fix: fix list_folder on s3

- pyproject.toml
- src/anemoi/utils/remote/s3.py
> chore: update to botocore>1.36

- src/anemoi/utils/provenance.py
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] I have performed a self-review of my code …
> fix: Remove the requirment to have git installed

- src/anemoi/utils/remote/s3.py
Add a function to check if a s3 object exists
> feat: add s3.object_exists() function

- src/anemoi/utils/commands/transfer.py
- src/anemoi/utils/remote/__init__.py
- src/anemoi/utils/remote/s3.py
Add a CLI to transfer data wrapping anemoi-utils. 
> feat: Add a CLI to transfer data

- src/anemoi/utils/dates.py
> feat: support negative timedelta

- src/anemoi/utils/dates.py
> feat: better support for negative timedeltas

- src/anemoi/utils/sanitise.py
- tests/test_sanitise.py
Add three levels of sanitation:
1. current behaviour (default)
2. remove hostnames but keep the rest of the url, paths and filenames
3. remove everything
Useful when sharing checkpoints with the public. Even though our URLs are generally protected, there's no reason to keep them in public metadata.
By opening this pull request, I affirm that all authors …
> feat(sanitise): Sanitation level

- src/anemoi/utils/config.py
An overlooked return needs fixing
> fix: Config override
